### ISSUE TITLE
Running pair_allegro with Kokkos on multiple GPUs

### ISSUE THREAD

**Issue by ryandeng1** [mir-group/pair_allegro#11]
Hi, I am trying to run pair_allegro with Kokkos on a system with 4 GPUs. I am creating 4 MPI processes with 1 GPU each.

The command looks something like this: `mpirun -d -x LD_LIBRARY_PATH -np 4 --mca pml ob1 --mca btl ^openib /home/ubuntu/lammps_install/bin/lmp -sf kk -k on g 1 -pk kokkos newton on neigh full < /home/ubuntu/md_allegro.in `

and I get an error saying "Specified device cuda:1 does not match device of data cuda:0". This occurs in the model forward call inside pair_allegro. I tried debugging and it seems that the device the model is initially loaded onto matches the data when later calling the compute method.

Not sure if the command I am running is incorrect or if it's some other issue. Thanks!

**Comment by anjohan** [comment]
Hi,

The `g` parameter should be set to the number of GPUs *per node*. See the [LAMMPS docs](https://docs.lammps.org/Speed_kokkos.html).
