### ISSUE TITLE
🐛 [BUG] Compilation of pair_allegro fails with `is protected within this context`

### ISSUE THREAD

**Issue by nicephore-bonnet** [mir-group/pair_allegro#17]
Hello,
I have an issue in compiling Lammps with the Nequip patch, as I get the following error after building with cmake (c compiler is gcc):

pair_allegro.cpp:129:33: error: ‘int LAMMPS_NS::NeighRequest::ghost’ is protected within this context
129 | neighbor->requests[irequest]->ghost = 1;

Thanks for your help,

Nicephore

**Comment by Linux-cpp-lisp** [comment]
See https://github.com/mir-group/pair_allegro/issues/8 for current version.

**Comment by nicephore-bonnet** [comment]
thanks!
