### ISSUE TITLE
Mix Allegro and LJ type pair styles

### ISSUE THREAD

**Issue by tgmaxson** [mir-group/pair_allegro#24]
I expect to be able to mix Allegro and other pair styles as follows in LAMMPS.

```
# DEFINE ALLEGRO MODEL
pair_style hybrid/overlay allegro lj/cut 2.5
pair_coeff * * MLFF.pth Pt Pd
pair_coeff 1 2 1 1.1 2.8
```

When I do this I get the following error

```
ERROR: Pair coeff for hybrid has invalid style (src/KOKKOS/pair_hybrid_overlay_kokkos.cpp:63)
```

I am guessing this is caused by Allegro not being supported in pair_hybrid with Kokkos?  Is this something easy to resolve?

**Comment by shuhaom** [comment]
Hi, you may change the script to

`pair_coeff allegro * * MLFF.pth Pt Pd`
`pair_coeff lj/cut 1 2 1 1.1 2.8`

**Comment by tgmaxson** [comment]
You are correct, you have to specify the pair_style as well, that was my mistake.

Correct code block looks like this for future reference.  The atom range has to come first.

```
pair_style hybrid/overlay allegro lj/cut 2.5
pair_coeff * * allegro MLFF.pth O H
pair_coeff 1 2 lj/cut 1 1.1 2.8
```

**Comment by Linux-cpp-lisp** [comment]
Glad this worked, thanks @shuhaom for responding.

Also for future reference there is support inside `nequip` for adding pair potential terms:
 - https://github.com/mir-group/nequip/blob/develop/configs/minimal_pair.yaml
 - https://github.com/mir-group/nequip/blob/develop/nequip/nn/pair_potential.py
Which takes it into account when training in addition to inference. Please note that the LJ version is pretty untested compared to the ZBL pair potential.

**Comment by tgmaxson** [comment]
Will this provide the terms to include in LAMMPS or are they included in the model file?  An example of how to actually train/run with LAMMPS using this would be very helpful.  I am using the stress branch of pair_allegro currently.

**Comment by Linux-cpp-lisp** [comment]
This will include them in the Allegro `.pth` file and you will *not* need to use `hybrid/overlay`. You will, of course, need to provide in the original Allegro YAML the LJ parameters. (For ZBL no parameters are required;  if you are just looking to have a core repulsion term you can try that first; we used it successfully, for example, in https://arxiv.org/abs/2304.10061.)
