### ISSUE TITLE
Any plan of updates for newer LAMMPS?

### ISSUE THREAD

**Issue by Chenghao-Wu** [mir-group/pair_allegro#30]
Hi Allegro developer teams,

Thank you very much for the helpful code to integrate Allegro into LAMMPS.

We found that the current 'pair_allegro' has some parts are not suppoted by the newer version of LAMMPS (after version from Jan2022).

Here are some example codes in pair_allegro.cpp, line 123:
```
// need a full neighbor list
  int irequest = neighbor->request(this,instance_me);
  neighbor->requests[irequest]->half = 0;
  neighbor->requests[irequest]->full = 1;

  neighbor->requests[irequest]->ghost = 1;
```
The variables "half", "full", "ghost" from neigh_request.h are protected in the newer version of LAMMPS(after version from Jan2022).

Any plan of  updates for newer LAMMPS?

Thank you for your time!

Best regards!

**Comment by Linux-cpp-lisp** [comment]
Hi @Chenghao-Wu ,

Thanks for your interest in our work!

These issues should be resolved on the development branch: https://github.com/mir-group/pair_allegro/tree/multicut

**Comment by Chenghao-Wu** [comment]
Found it! Thank you for your swift reply, Albert.
