### ISSUE TITLE
Issue with multiple species system

### ISSUE THREAD

**Issue by PythonFZ** [mir-group/pair_allegro#4]
I'm struggeling to run a MD using lammps with either `pair_nequip` or `pair_allegro` on a system of 5 different species.
For the nequip model I was able to run a MD using ASE, for allegro I could not get the ASE calculator to work yet (is this a known issue?).

I'm using

```
#############################
### Configure system type ###
#############################

units           metal
boundary        p p p
atom_style      atomic

read_data system.lmp_data

mass 1 10.811
group B type 1

mass 2 12.011
group C type 2

mass 3 18.998403
group F type 3

mass 4 1.00784
group H type 4

mass 5 14.0067
group N type 5


replicate     4 4 4
velocity        all create 303.15 132465

pair_style   allegro  # nequip
pair_coeff   * * deployed.pth H B C N F

timestep        0.001
```

and checked that the order matches `nequip-deply info deployed.pth`

I validated nequip / allegro pair styles using a two body system of KCl which worked nicely.
For this model I get:

```
       0            0       303.15    1.1985879    4009.6546 
[uc2n508.localdomain:2015923] 2 more processes have sent help message help-mpi-btl-openib.txt / default subnet prefix
[uc2n508.localdomain:2015923] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
       1        0.001    19324.723    1.1985879    255601.07 
       2        0.002            0    1.1985879            0 
       3        0.003            0    1.1985879            0 
       4        0.004            0    1.1985879            0 
       5        0.005            0    1.1985879            0 
       6        0.006            0    1.1985879            0 
       7        0.007            0    1.1985879            0 
       8        0.008            0    1.1985879            0 
       9        0.009            0    1.1985879            0
```

The model metrics are:

|validation_loss_f|validation_loss_e|
|---|---|
|0.00235|8.9e-6| 

They can certainly be optimized but I would not expect the model to explode immediately.
I tried different input files and trained a different model with no change so far.
Because I am able to run the model using ASE, do you think this could be related to the pair_style?

**Comment by Linux-cpp-lisp** [comment]
cc @simonbatzner 

@PythonFZ , I'm not entirely following what you're saying here--- am I correct in understanding that, for models trained on this two-species KCl system,

- nequip, ASE works
- nequip, LAMMPS works
- allegro, ASE works
- allegro, LAMMPS fails

where "works" or "fails" indicates "does not blow up."

As always, while I don't expect there to be a failure, I'd encourage you to run the `pair_nequip` and `pair_allegro` unit tests to confirm that everything is OK with your install. You can also see how you can pretty easily modify the unit tests to use your data and model hyperparameters if you want to thoroughly check the produced forces, etc. (see https://github.com/mir-group/pair_nequip/blob/main/tests/test_python_repro.py#L26-L46).

**Comment by Linux-cpp-lisp** [comment]
Your atom type definitions look like they may be wrong: you seem to want, for example, LAMMPS atom type 4 to be Hydrogen, but are assigning it NequIP/Allegro type `N` (the fourth NequIP type you list).

From the [README](https://github.com/mir-group/pair_allegro#usage-in-lammps):
```
The names after the model path deployed.pth indicate, in order, the names of the Allegro model's atom types to use for LAMMPS atom types 1, 2, and so on. The number of names given must be equal to the number of atom types in the LAMMPS configuration (not the Allegro model!). The given names must be consistent with the names specified in the Allegro training YAML in chemical_symbol_to_type or type_names.
```
I guess we could explain this more explicitly.

Given your masses/LAMMPS group labels, I think the correct line would be:
```
pair_coeff   * * deployed.pth B C F H N
```

**Comment by Linux-cpp-lisp** [comment]
I've also clarified this in the README.

**Comment by PythonFZ** [comment]
Thanks a lot! With the new atom types everything worked as expected.
